# Generated by Django 5.1.7 on 2025-04-04 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='video_link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='media',
            name='advertiser',
        ),
    ]
