# Generated by Django 5.1.7 on 2025-04-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_rename_video_link_media_url_remove_media_advertiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='category',
            field=models.CharField(choices=[('Youtube', 'Youtube'), ('Tiktok', 'Tiktok'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Telegram', 'Telegram')], default='Youtube', max_length=255),
        ),
    ]
