# Generated by Django 5.1.7 on 2025-04-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_media_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='coins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
