# Generated by Django 5.1.7 on 2025-04-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_media_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
