# Generated by Django 5.1.7 on 2025-04-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_media_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedmedia',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
