# Generated by Django 5.1.7 on 2025-04-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_watchedmedia_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='duration',
            field=models.TimeField(null=True),
        ),
    ]
