# Generated by Django 5.1.7 on 2025-04-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_media_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
