# Generated by Django 5.1.7 on 2025-04-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_transaction_tx_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='plan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
