# Generated by Django 5.1.7 on 2025-04-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_coins_customuser_limits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='limits',
            new_name='watch_limit',
        ),
    ]
