# Generated by Django 5.1.7 on 2025-04-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_limits_customuser_watch_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='watch_limit',
        ),
        migrations.AddField(
            model_name='customuser',
            name='videos_watched',
            field=models.IntegerField(default=0),
        ),
    ]
