# Generated by Django 5.1.7 on 2025-04-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_customuser_watch_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coin_multiplier',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='watch_limit',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
    ]
