# Generated by Django 5.1.7 on 2025-04-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_coin_multiplier_customuser_watch_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='watch_limit',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
