# Generated by Django 5.1.7 on 2025-04-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_watch_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription',
            field=models.CharField(default='Basic'),
        ),
    ]
